### ISSUE TITLE
To-Do List : PA Review

### ISSUE THREAD

**Issue by hkumar1993** [hkumar1993/BaseJump#19]

**Comment by rkoeze** [comment]
I can't add a todo at the moment. Is that working locally?

**Comment by rkoeze** [comment]
Also, let's seed each project with more todos. Finance, Human Resources, etc. should all have filled out lists. That's adequately seeded.

**Comment by hkumar1993** [comment]
@rkoeze seems to be working on my end and on heroku. I'll seed up the databse and let you know once thats complete

**Comment by rkoeze** [comment]
Cool! Ping me when they're seeded. Thanks!

**Comment by hkumar1993** [comment]
@rkoeze todos have been seeded

**Comment by rkoeze** [comment]
beautiful!
