### ISSUE TITLE
Schedules : PA Review

### ISSUE THREAD

**Issue by hkumar1993** [hkumar1993/BaseJump#21]

**Comment by rkoeze** [comment]
Looks good overall. One quick question:

When I'm at `http://basejumpapp.herokuapp.com/#/1/projects/1/events` why do the `Interview with Harsh` and `Company Anniversary` always show up, regardless of the day?

**Comment by hkumar1993** [comment]
I think I should label the list correctly, all events listed are uupcoming events. If you click on a date after October 6th,  Interview with Harsh should disappear

**Comment by rkoeze** [comment]
Cool. If we can differentiate between upcoming events and events that day, as well as seed, we're good to go.
